### ISSUE TITLE
DAG disappeared from wallet.

### ISSUE THREAD

**Issue by Maezzzzz** [grvlle/constellation_wallet#121]
Hello, I had logged into my constellation wallet which last has roughly 50k dag in it to find the total stating that I had 0 DAG.

**Comment by digitaltwinnn** [comment]
Hi Maezzzzz, at that time the constellation network was undergoing some maintenance. I'll think of something to display this in the wallet (instead of it displaying 0 DAGs) if that happens. If you try again now it should be fine and display your balance correctly.

**Comment by grvlle** [comment]
This has been tested and fixed as part of the linked PR pushed by @digitaltwinnn .
