### ISSUE TITLE
Unable to send DAG through Molly Wallet 1.2.0 on Windows 10

### ISSUE THREAD

**Issue by jrmore98** [grvlle/constellation_wallet#134]
Essentially what the title states, for about a week now anytime I attempt to deposit to my wallet on Kucoin it fails and I get the same notification every time. 
![mollywalleterror](https://user-images.githubusercontent.com/75861102/101951941-7869f600-3bbd-11eb-8144-a23cf06ea605.png)
I am on Windows 10 Pro Version 20H2. I can't imagine it would be an issue but my PC is connected to the internet via a Wi-Fi card not Ethernet. If I can provide any extra information to help please let me know.

**Comment by ffox77** [comment]
Molly Wallet is now being supported by Stardust Collective github. You can get the latest release 2.1 from: https://github.com/StardustCollective/molly_wallet/releases
