### ISSUE TITLE
Unable to create database object for the imported wallet. Maybe it has already been imported? Try to login.

### ISSUE THREAD

**Issue by wieczorslawo** [grvlle/constellation_wallet#172]
Trying to log in after one year or so and the latest Molly wallet returns me this error.
`Unable to create database object for the imported wallet. Maybe it has already been imported? Try to login.`

I'm sure I entered proper credentials.

![image](https://github.com/grvlle/constellation_wallet/assets/26138717/3a996152-33f3-4101-8a03-9bec65fbb3d5)

**Comment by wieczorslawo** [comment]
Please note that I didn't previously import on that machine

**Comment by marcinwadon** [comment]
Try this: https://chrome.google.com/webstore/detail/stargazer-wallet/pgiaagfkgcbnmiiolekcfmljdagdhlcm

**Comment by wieczorslawo** [comment]
Stargazer has the word phrase wallet restore. I placed my DAGs in the Molly wallet some time ago. And it requires private key, key alias, keystore password and key password.

**Comment by wieczorslawo** [comment]
Is there any way to use my private key from Molly to import dags within the Stargazer wallet?

**Comment by marcinwadon** [comment]
I will let [@Alex Brandes](https://github.com/AlexBrandes) speak for that

**Comment by wieczorslawo** [comment]
Ok found it, please use fork from here: https://github.com/StardustCollective/molly_wallet/releases/tag/v2.2.0
It allows to migrate old p12 cert to json as well
