### ISSUE TITLE
Windows - Separate cards in Settings

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#26]
Separate cards in Settings for 
Toggle Dashboard Widgets and Backup / Restore

![image](https://user-images.githubusercontent.com/56271216/71355023-0d737980-257e-11ea-84dc-4d0613f4433a.png)

**Comment by grvlle** [comment]
The settings page has received a design overhaul in 0.18-beta. This has also been addressed. Thank you.
