### ISSUE TITLE
Sierra 10.12.6 Issues

### ISSUE THREAD

**Issue by cryptonando** [grvlle/constellation_wallet#31]
Hi,

After downloading the pre-compiled version on my Mac which is on Sierra I can't run the app. And the icon of the app is missing..

/Users/nandoeweg/Desktop/Screen Shot 2020-02-06 at 08.54.45.png

Cheers,
Nando

**Comment by cryptonando** [comment]
I clicked "open package contents" and clicked on the mollywallet to see what would happen.. Terminal started and a tekst appeared.. Now I have to find a way how to upload it here...

**Comment by cryptonando** [comment]
Last login: Thu Feb  6 08:46:36 on console
Nandos-Mac-Pro:~ nandoeweg$ /Applications/Molly\ -\ Constellation\ Desktop\ Wallet\ \[Beta\].app/Contents/MacOS/mollywallet ; exit;
dyld: lazy symbol binding failed: Symbol not found: _objc_alloc_init
  Referenced from: /Applications/Molly - Constellation Desktop Wallet [Beta].app/Contents/MacOS/mollywallet
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_alloc_init
  Referenced from: /Applications/Molly - Constellation Desktop Wallet [Beta].app/Contents/MacOS/mollywallet
  Expected in: /usr/lib/libobjc.A.dylib

SIGABRT: abort
PC=0x13bb89ee m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x45b1210, 0xc00007fbd8, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc00007fba8 sp=0xc00007fb70 pc=0x400536b
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewCreate(0x32f000005fa, 0x8100020, 0x8100050, 0x0, 0x0)
	_cgo_gotypes.go:97 +0x4e fp=0xc00007fbd8 sp=0xc00007fba8 pc=0x44437de
github.com/wailsapp/wails/lib/renderer/webview.NewWebview(0x46ecc32, 0x2b, 0x0, 0x0, 0x5fa, 0x32f, 0x0, 0xc0000c4330, 0xa, 0xe)
	/Users/mwadon/go/pkg/mod/github.com/wailsapp/wails@v0.19.0-pre2/lib/renderer/webview/webview.go:261 +0xfe fp=0xc00007fc38 sp=0xc00007fbd8 pc=0x44442ee
github.com/wailsapp/wails/lib/renderer.(*WebView).Initialise(0xc0000d0180, 0x4ca0940, 0xc0001be180, 0x4c9bac0, 0xc0000d0240, 0x4c9ca00, 0xc000126000, 0x0, 0x0)
	/Users/mwadon/go/pkg/mod/github.com/wailsapp/wails@v0.19.0-pre2/lib/renderer/webview.go:52 +0x358 fp=0xc00007fd30 sp=0xc00007fc38 pc=0x4447ec8
github.com/wailsapp/wails.(*App).start(0xc0001be100, 0x0, 0x0)
	/Users/mwadon/go/pkg/mod/github.com/wailsapp/wails@v0.19.0-pre2/app.go:100 +0x197 fp=0xc00007fe68 sp=0xc00007fd30 pc=0x444be97
github.com/wailsapp/wails.(*App).Run(0xc0001be100, 0x46c5dc0, 0xc000110600)
	/Users/mwadon/go/pkg/mod/github.com/wailsapp/wails@v0.19.0-pre2/app.go:79 +0xaf fp=0xc00007fee0 sp=0xc00007fe68 pc=0x444bbcf
main.main()
	/Users/mwadon/Projects/constellation-labs/constellation_wallet/main.go:29 +0x23e fp=0xc00007ff60 sp=0xc00007fee0 pc=0x447d43e
runtime.main()
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203 +0x21e fp=0xc00007ffe0 sp=0xc00007ff60 pc=0x403198e
runtime.goexit()
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00007ffe8 sp=0xc00007ffe0 pc=0x405d321

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/usr/local/Cellar/go/1.13.6/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.13.6/libexec/src/os/signal/signal_unix.go:29 +0x41

rax    0x2000209
rbx    0x4
rcx    0x7fff5fbfe878
rdx    0x7fff5fbfecf0
rdi    0x6
rsi    0x4
rbp    0x7fff5fbfe8d0
rsp    0x7fff5fbfe878
r8     0x7fff5fbfe8f0
r9     0x0
r10    0x97
r11    0x246
r12    0x97
r13    0x7fff5fbfecf0
r14    0x6
r15    0x0
rip    0x13bb89ee
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by marcinwadon** [comment]
@cryptonando I cannot see the image in the first message. Can you confirm it's the same or similar to that one?

![image](https://user-images.githubusercontent.com/4959931/73924243-76177b00-48cc-11ea-8ee9-32753cc06b56.png)

**Comment by cryptonando** [comment]
Ha Marcin,

No nothing happends after opening the app. 
 The screenshot was of the missing icon..

Might have to do with the older osx system. 

Cheers,
Nando

Verstuurd vanaf mijn iPhone

**Comment by grvlle** [comment]
Hi Nando,

We officially only support Catalina. In order for us to support more version of MacOS, the wallet itself needs to be compiled on the OS version in question. The library still lacks support for cross-compilation. If you, or anyone you know can compile it following the instructions in the readme, then I'm pretty positive it would run on Sierra as well. But this is still unverified. 

I will open a new ticket for wider range of OS support and include Sierra in there. Thank you for creating this issue and I sincerely hope we manage to provide support with the next release.
