### ISSUE TITLE
Windows Click link in Terms & Conditions opens webpage error

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#32]
Clicking on www.constellationnetwork.io in terms and conditions sends you to an 'website for sale' page with script error. Then you have to force close the wallet and login. And then terms and conditions doesn't pop up again even though I haven't accepted them

Same with the second link further down in the text

![1](https://user-images.githubusercontent.com/56271216/73920889-9ba18600-48c6-11ea-81f0-c8aca5c07ca5.JPG)
![2](https://user-images.githubusercontent.com/56271216/73920893-9d6b4980-48c6-11ea-9a7a-6a264b220674.JPG)

**Comment by grvlle** [comment]
This has been resolved in 017-Beta.
