### ISSUE TITLE
Windows Scrollbar in Terms and Conditions is too close to text.

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#33]
Scrollbar in Terms and Conditions is too close to text.

Can you add a border?

![1](https://user-images.githubusercontent.com/56271216/73921008-d3103280-48c6-11ea-8295-4261c128bbc3.JPG)

**Comment by grvlle** [comment]
Fixed this with the latest commit to 017-Beta
