### ISSUE TITLE
Windows There is a mix of capital and non-capital letters in wallet address

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#36]
There is a mix of capital and non-capital letters in wallet address

_Originally posted by @InfiniteDAGl00p in https://github.com/grvlle/constellation_wallet/issues/22#issuecomment-583014488_

**Comment by grvlle** [comment]
That's actually intentional. Constellation Team is leveraging Base58 encoding for the addresses that they produce. One fundamental part of that encoding scheme is to include capital and non-capital lettering in the hash it produces. https://en.wikipedia.org/wiki/Base58
