### ISSUE TITLE
Windows Add check mark or confirmation when changing wallet information

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#38]
Add check mark or confirmation when changing wallet information
No sign of the change happened when you enter your own wallet information now

![image](https://user-images.githubusercontent.com/56271216/73962397-a41daf00-490e-11ea-83c9-6cbdb11370df.png)

**Comment by grvlle** [comment]
Introduced into the 017-Beta branch.
