### ISSUE TITLE
Windows Mouse pointer does not change to a 'finger' on Logout button

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#39]
Mouse pointer does not change to a 'finger' on Logout button

It turns into a text marker icon

![image](https://user-images.githubusercontent.com/56271216/73963938-89990500-4911-11ea-9ff5-c9419da857a2.png)

**Comment by grvlle** [comment]
This will be fixed as part of v.2.0 of the https://github.com/wailsapp/wails library. Will leave this open until that has been released and the code base has been merged.

**Comment by grvlle** [comment]
Fixed as part of 018-beta branch.
