### ISSUE TITLE
Windows When logged out of wallet, existing key in Create Wallet form

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#40]
When logging out of a wallet and going to 'create wallet' the key form is populated with the old wallet key.
This makes it very easy to overwrite the old wallet key.... And all your funds are gone!

![image](https://user-images.githubusercontent.com/56271216/73964205-0f1cb500-4912-11ea-9fce-99838b60643e.png)

**Comment by grvlle** [comment]
A fix has been implemented with the 0.17 Beta release. Thanks for reporting.
