### ISSUE TITLE
All OS: Loading/processing icon.

### ISSUE THREAD

**Issue by StrannikAD** [grvlle/constellation_wallet#41]
![image](https://user-images.githubusercontent.com/22587768/74078182-20cd9c00-4a7b-11ea-98b1-a0c9153dc78d.png)

**Issue:**
- When clicking the "Create" button - the system is thinking but there is no indication that it is doing so. Anyone who continues to click the "create" button will potentially stop the original create wallet process and will receive an error "Alias already exists".

**Proposed Solution**
- Include a loading overlay for this screen. 
Examples:
https://www.npmjs.com/package/vue-loading-overlay
https://madewithvuejs.com/c/loading-animations

- Disable the "create" button for users while the wallet creation process is ongoing.

**Comment by grvlle** [comment]
I've introduced changes in the v.0.17-Beta branch that'll disable the button upon loading. In addition to that there's also a loading bar up top that I've made into a more visible color. Kudos on the clearly described issue!
