### ISSUE TITLE
Front End Suggestions - Create Wallet Page

### ISSUE THREAD

**Issue by StrannikAD** [grvlle/constellation_wallet#42]
Old Behaviour:

- There are some inconsistencies in the naming conventions between the definitions and the form headings.

Proposed Behaviour: 

- Slight naming adjustments
<img width="1420" alt="Screen Shot 2020-02-08 at 5 37 29 pm" src="https://user-images.githubusercontent.com/22587768/74080722-3783eb00-4a9b-11ea-9b9c-cd9497964123.png">

- Also realised that I forgot to mark the "KeyStore File/Key File" naming convention. Depending on the preferred name - I think it makes sense to have it consistently across the page to avoid user confusion.

@grvlle - if you are happy with the suggested changes, I am happy to create a PR for you to review.

**Comment by grvlle** [comment]
I agree 100%. Would be happy to review a PR.

**Comment by grvlle** [comment]
Fixed in 0.17-beta.
