### ISSUE TITLE
Generic: Add 'Max amount' button on send transaction screen

### ISSUE THREAD

**Issue by InfiniteDAGl00p** [grvlle/constellation_wallet#53]
Add 'Max amount' button on send transaction screen

If you want to send all your DAG from your wallet you have to copy/paste your balance from the dashboard window, and when you go back to Transaction windows the recipient address is gone.

Alternatively your amount of DAG can be show in the top of all windows.

**Comment by grvlle** [comment]
It would be cool to introduce a means of sending a certain percentage of the amount similar to a lot of tier 1 exchanges. Will consider this. Thanks

**Comment by grvlle** [comment]
This has been included in the 018-beta release that's merged with Master right now. Kudos to @digitaltwinnn for making this implementation.
