### ISSUE TITLE
Bug in Java OpenJDK (only v8) prevents wallet to create/open the keystore

### ISSUE THREAD

**Issue by digitaltwinnn** [grvlle/constellation_wallet#54]
Note: the wallet works perfectly fine on OpenJDK v9 but not on v8.

Operating System: Microsoft Windows [Version 10.0.18363.657]
Java Open JDK: openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

Debug log from the Molly wallet: Unable to generate wallet address. Reason: exit status 1: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.3.132.0.10

**Comment by grvlle** [comment]
Good find. I've updated the readme on the v.0.18 branch.
