### ISSUE TITLE
Input forms are tiny on some systems

### ISSUE THREAD

**Issue by grvlle** [grvlle/constellation_wallet#60]
This was introduced as part of [PR #59 ](https://github.com/grvlle/constellation_wallet/pull/59).

![2020-03-03_583x715_scrot](https://user-images.githubusercontent.com/25682690/75782821-d11f7f00-5d5f-11ea-8cb2-bcbf861c1679.png)

Not sure if there are any easy fix while still maintain smooth scaling across resolutions. It's not a blocker.

I loosely assigned you @digitaltwinnn as I suspect you may have a better understanding of this.

**Comment by digitaltwinnn** [comment]
Thanks for checking this. Found it and just pushed a fix for it (partially rolled back a small change I did in PR#59) with some other minor improvements. Let me know if this works better

**Comment by grvlle** [comment]
Input forms are still very narrow on my system. However now the buttons align very nicely when reducing the size of the window. I love that!

Also noticed that the wallet image is very small.
![2020-03-04_1919x1025_scrot](https://user-images.githubusercontent.com/25682690/75828714-c808cf00-5dac-11ea-853e-2b929b0c0ebe.png)

I suppose they're scaling correctly with my resolution. Although I would still want to increase the size for the wallet image, as well as making the form groups a bit taller. 

I guess the avatar image can simply be increased: https://github.com/grvlle/constellation_wallet/blob/cd6d8f9b8f5d6ccd0e2a6e8f1bd3704ebb993cb6/frontend/src/assets/sass/paper/_cards.scss#L65

Does it look good in size on your resolution? Will try on my 4k monitor tomorrow.

**Comment by digitaltwinnn** [comment]
What resolution is your currently system? For anything wider than bootstrap xl (1200 pixel width) it now starts to upscale the fonts, however currently only slightly by 2x from 1200px to 4k (i.e. not with 1:1 ratio). You can play with the ratio and increase it closer to 1:1 to avoid still rather tiny fonts on higher resolutions.
https://github.com/grvlle/constellation_wallet/blob/d62bc9e2b2dc99b11c81f095fab33a0276e097e3/frontend/src/assets/sass/paper/_responsive.scss#L485

We may also need to add the $line-height variable here and apply the same ratio as well.

**Comment by digitaltwinnn** [comment]
Regarding the sizing of the images I'll have a closer look as there are several ones like in the navigation bar, login page, avatar, etc. They should scale but they use size em (relative to parent) vs rem (relative to page). If em's are nested they are relative to eachother so they scale but not always with a 1:1 ratio like rem will always do.

**Comment by grvlle** [comment]
> What resolution is your currently system? For anything wider than bootstrap xl (1200 pixel width) it now starts to upscale the fonts, however currently only slightly by 2x from 1200px to 4k (i.e. not with 1:1 ratio). You can play with the ratio and increase it closer to 1:1 to avoid still rather tiny fonts on higher resolutions.
> https://github.com/grvlle/constellation_wallet/blob/d62bc9e2b2dc99b11c81f095fab33a0276e097e3/frontend/src/assets/sass/paper/_responsive.scss#L485
> 
> We may also need to add the $line-height variable here and apply the same ratio as well.

Thanks @digitaltwinnn !

I opted in to change the font size in the form groups across all resolutions instead as part of this commit: https://github.com/grvlle/constellation_wallet/commit/f9578cc2bf6cecd25928bc6c22ef782d589cfa4f

Looks great now on both my 4k and 2k screen. Let me know if it looks poorly on yours and I'll adjust accordingly.

**Comment by grvlle** [comment]
> Regarding the sizing of the images I'll have a closer look as there are several ones like in the navigation bar, login page, avatar, etc. They should scale but they use size em (relative to parent) vs rem (relative to page). If em's are nested they are relative to eachother so they scale but not always with a 1:1 ratio like rem will always do.

Awesome! Thanks for looking into it. I'll go ahead and close this ticket for now as I've pushed a commit that should resolve the original issue.
