### ISSUE TITLE
Query nodes directly for pending Transactions

### ISSUE THREAD

**Issue by buckysballs** [grvlle/constellation_wallet#71]
Currently Molly downloads previously submitted Transactions from the Block Explorer endpoints, but those don't contain Transactions that are pending or accepted but not migrated to storage. Thus, in the case of retrieving an account's transaction history, we'll need to query the load balancer as well. The mempool can be queried via the 

/transaction/<hash> 

endpoint which returns all transactions from mempool. The responses from that endpoint are the following:

- if transaction exists and there is empty checkpoint block -> unprocessed
- if transaction exists and there is checkpoint block -> processed, waiting for snapshot
- if transaction doesn’t exists -> either unprocessed or already in snapshot (should be available in block explorer then)

DoD)
- Query for pending transactions when the wallet downloads account chain data

**Comment by grvlle** [comment]
Implemented.
