### ISSUE TITLE
window size out of screen bounds

### ISSUE THREAD

**Issue by bh90210** [grvlle/constellation_wallet#80]
hello there,
not sure if a bug or not but on my 13 inches screen (linux ubuntu) since the window isn't resizeable I can't really access parts of the app.

**Comment by grvlle** [comment]
Hey,

Thanks for using the wallet. Seems that you've installed an outdated version. See this https://github.com/grvlle/constellation_wallet/releases for the latest builds.

**Comment by bh90210** [comment]
yeap, it works! thanks.
fiy I first downloaded the linux version from the website :+1:
