### ISSUE TITLE
Cannot open Mac wallet

### ISSUE THREAD

**Issue by cryptorico** [grvlle/constellation_wallet#83]
Downloaded the Mac wallet. Message "The application Molly - Constellation Desktop Wallet can't be open" appears after trying to install.

<img width="422" alt="Screenshot 2020-05-14 at 10 52 52" src="https://user-images.githubusercontent.com/32385628/81887239-3f3eb880-95d1-11ea-85b6-f122fedf4e7b.png">

**Comment by grvlle** [comment]
Hey cryptorico,

See [this section](https://github.com/grvlle/constellation_wallet/blob/develop/docs/faq.md#q-why-am-i-getting-the-application-molly---constellation-desktop-wallet-cant-be-opened) of the F.A.Q.
