### ISSUE TITLE
Unable to parse the last transaction. Reason unexpected end of JSON input

### ISSUE THREAD

**Issue by teltel123** [grvlle/constellation_wallet#91]
When trying to send DAG to an address I get the following error message:
"Unable to parse the last transaction. Reason unexpected end of JSON input"
![dag](https://user-images.githubusercontent.com/65632386/82387421-fb024c80-9a04-11ea-8952-2574b5a23eb3.jpg)

wallet.log is empty

**Comment by grvlle** [comment]
Hey teltel123,

Please see this section of the FAQ. 
https://github.com/grvlle/constellation_wallet/blob/develop/docs/faq.md#q-why-am-i-getting-an-error-when-sending-transaction

**Comment by teltel123** [comment]
Hi,
After deleting the .dag folder I am not able getting access to the wallet anymore. I'm 100% certain that the wallet file & Key Alias is correct and it has worked before deleting the .dag folder.
![dag2](https://user-images.githubusercontent.com/65632386/82466428-680df480-9a8e-11ea-82b1-a953112eb340.jpg)

**Comment by grvlle** [comment]
Hey @teltel123,

After deleting the .dag folder, you need to import the wallet again. The button is located under the login button.
