### ISSUE TITLE
Logout the user automatically when idle for too long

### ISSUE THREAD

**Issue by digitaltwinnn** [grvlle/constellation_wallet#95]
To avoid that the wallet stays open while not actively used, we could logout the user automatically when they have been idle too long. The idle time we could make configurable in the Settings page.

**Comment by grvlle** [comment]
Fully agree. Since this is security related I propose we strive to implement this for the next release. I'll set up a project page to be able to better prioritize.

**Comment by grvlle** [comment]
Merged. Kudos @digitaltwinnn
